"""empty message

Revision ID: 84b500d3b8b5
Revises: 
Create Date: 2024-02-17 13:17:19.810952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84b500d3b8b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
